export type Emotion = "neutral" | "happy" | "sad";

// ============================================================
// Unity -> React (window.parent.postMessage from inside the iframe)
// ============================================================

export interface UnityReadyEvent {
  type: "UNITY_READY";
}
export interface StageChangedEvent {
  type: "STAGE_CHANGED";
  stage: number;
}
export interface AudioRecordedEvent {
  type: "AUDIO_RECORDED";
  blobUrl: string;
  duration: number;
}
export interface SessionCompleteEvent {
  type: "SESSION_COMPLETE";
  summary: Record<string, unknown>;
}

export type UnityToReactEvent =
  UnityReadyEvent | StageChangedEvent | AudioRecordedEvent | SessionCompleteEvent;

const UNITY_TO_REACT_TYPES = new Set<UnityToReactEvent["type"]>([
  "UNITY_READY",
  "STAGE_CHANGED",
  "AUDIO_RECORDED",
  "SESSION_COMPLETE",
]);

// postMessage payloads are `unknown` by nature — validate the shape before
// trusting anything coming out of the iframe.
export function isUnityToReactEvent(data: unknown): data is UnityToReactEvent {
  if (typeof data !== "object" || data === null || !("type" in data)) return false;
  const type = (data as { type: unknown }).type;
  return typeof type === "string" && UNITY_TO_REACT_TYPES.has(type as UnityToReactEvent["type"]);
}

// ============================================================
// React -> Unity (iframe.contentWindow.postMessage), sent as an
// explicit {command, payload} envelope so Unity has a discriminant
// to dispatch on.
// ============================================================

export interface OnSessionInitCommand {
  command: "OnSessionInit";
  payload: { scenarioId: string; userId: string };
}
// Same 4-dimension rubric used everywhere a VR round's spoken feedback is
// AI-scored — see FeedbackLabWeb/src/lib/ai.server.ts (generateCoachingReport/
// generateRoundTwoReport) and the COMPETENCIES array in
// routes/_authenticated/vr-simulation.tsx.
// Kept as one shape so Unity, the scoring function, and the UI can never
// drift into three different schemas again (that happened once already).
export interface RubricScores {
  speechClarity: number;
  linguisticAppropriateness: number;
  balance: number;
  intentConsistency: number;
}

export interface OnScoresReceivedCommand {
  command: "OnScoresReceived";
  payload: RubricScores;
}
// retryLine carries the exact line the student should say before the
// teacher gives Round 2 feedback (Scenario.studentLineRetry in
// vr-simulation.tsx) — sent explicitly instead of hardcoding scenario text
// on the Unity side, so it stays the single source of truth. See
// ScenarioManager.ReloadForRetry(string) in FeedbackLabsVR, which passes it
// straight to SalsaTTSLinker.Speak().
export interface OnRetryRequestedCommand {
  command: "OnRetryRequested";
  payload: { scenarioId: string; retryLine: string };
}
export interface OnEmotionalFeedbackCommand {
  command: "OnEmotionalFeedback";
  payload: { emotion: Emotion };
}
// Lets the user mute Unity's audio (NPC presentation/TTS playback) from the
// React side so they can skip straight to speaking into the mic without
// waiting for/listening to the presentation — see the mute button in
// UnityPlayer.tsx. Unity applies it globally via AudioListener.volume
// (see WebGLBridge.OnMuteToggle).
export interface OnMuteToggleCommand {
  command: "OnMuteToggle";
  payload: { muted: boolean };
}

export type UnityCommand =
  | OnSessionInitCommand
  | OnScoresReceivedCommand
  | OnRetryRequestedCommand
  | OnEmotionalFeedbackCommand
  | OnMuteToggleCommand;

// ============================================================
// Consolidated LLM coaching report — Round 1 (Stage 3) and Round 2
// (Stage 4). Generated by generateCoachingReport / generateRoundTwoReport
// in FeedbackLabWeb/src/lib/ai.server.ts, from the teacher's spoken
// transcript PLUS presentation context (see PresentationContext below).
// One consolidated response replaces the old fragmented
// scoreFeedbackEmotion + scoreFeedbackRubric + client-side threshold
// strengths/weaknesses + hardcoded coaching template + static goal list.
// ============================================================

// What was actually presented in Unity — sent alongside the transcript so
// the LLM can judge whether the teacher's feedback actually matches what
// the student presented (not just generic feedback quality in a vacuum).
export interface PresentationContext {
  studentName: string;
  persona: string;
  courseContext: string;
  activity: string;
  behaviors: string[];
  presentationScript?: string;
  // Scenario-specific coaching criteria pulled from that scenario's
  // Instructional Design Manual (Assessment Focus + Expected Learner
  // Behaviour + the "what makes this low-quality" cues from the VR Scenario
  // Script) — e.g. Scenario 2's "Specific Praise / Growth Mindset" lens vs
  // Scenario 3's "Behavior-focused / Psychological Safety" lens. The rubric
  // schema itself (RubricScores above) stays the ONE canonical 4-dimension
  // shape across every scenario — this field doesn't add new dimensions, it
  // tells the LLM how to *interpret* balance/intentConsistency/etc. for this
  // particular scenario. Optional: scenarios without one (S1, S4, S5 stubs)
  // just get the generic rubric description in the system prompt.
  assessmentFocus?: string;
}

// Round 1 (Stage 3: Abstract Conceptualization) — one call produces
// everything steps 3.1-3.5 need.
export interface CoachingReport {
  rubric: RubricScores;
  emotion: Emotion;
  strengths: string[];
  weaknesses: string[];
  personalizedRecommendation: string;
  suggestedGoals: string[];
  // A genuine critique of the specific goal the teacher wrote for themselves
  // in Stage 2's reflection (personalGoal), given the actual transcript/
  // rubric — not a static "well done" caption. Empty string if no goal was
  // set (defensive; Stage2Reflection currently requires one).
  personalGoalFeedback: string;
}

// Round 2 (Stage 4: Active Experimentation) — lighter schema. No
// strengths/weaknesses/recommendation/goals since there's no Round 3 to
// feed into; adds an improvementSummary aware of the goals the teacher set
// and how transcript 2 compares to transcript 1.
export interface RoundTwoReport {
  rubric: RubricScores;
  emotion: Emotion;
  improvementSummary: string;
}

// Final Summary step — a genuinely fresh LLM call over BOTH rounds together
// (transcripts + rubric scores + the goals set after Round 1), not assembled
// from CoachingReport's Round-1-only strengths/weaknesses/recommendation.
// See generateFinalSummary in ai.server.ts.
export interface FinalSummaryReport {
  goalAchievement: string;
  strengths: string[];
  weaknesses: string[];
  recommendation: string;
}
