/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SwissRouteImport } from './routes/swiss'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticRouteImport } from './routes/_authenticated/diagnostic'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPosttestRouteImport } from './routes/_authenticated/posttest'
import { Route as AuthenticatedSurveyRouteImport } from './routes/_authenticated/survey'
import { Route as AuthenticatedVrSimulationRouteImport } from './routes/_authenticated/vr-simulation'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUserIdRouteImport } from './routes/admin/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SwissRoute = SwissRouteImport.update({
  id: '/swiss',
  path: '/swiss',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticRoute = AuthenticatedDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosttestRoute = AuthenticatedPosttestRouteImport.update({
  id: '/posttest',
  path: '/posttest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurveyRoute = AuthenticatedSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVrSimulationRoute =
  AuthenticatedVrSimulationRouteImport.update({
    id: '/vr-simulation',
    path: '/vr-simulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdRoute = AdminUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/swiss': typeof SwissRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/posttest': typeof AuthenticatedPosttestRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/vr-simulation': typeof AuthenticatedVrSimulationRoute
  '/admin/$userId': typeof AdminUserIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/swiss': typeof SwissRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/posttest': typeof AuthenticatedPosttestRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/vr-simulation': typeof AuthenticatedVrSimulationRoute
  '/admin/$userId': typeof AdminUserIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/swiss': typeof SwissRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/posttest': typeof AuthenticatedPosttestRoute
  '/_authenticated/survey': typeof AuthenticatedSurveyRoute
  '/_authenticated/vr-simulation': typeof AuthenticatedVrSimulationRoute
  '/admin/$userId': typeof AdminUserIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/swiss'
    | '/consent'
    | '/dashboard'
    | '/diagnostic'
    | '/modules'
    | '/onboarding'
    | '/overview'
    | '/posttest'
    | '/survey'
    | '/vr-simulation'
    | '/admin/$userId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/swiss'
    | '/consent'
    | '/dashboard'
    | '/diagnostic'
    | '/modules'
    | '/onboarding'
    | '/overview'
    | '/posttest'
    | '/survey'
    | '/vr-simulation'
    | '/admin/$userId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/swiss'
    | '/_authenticated/consent'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostic'
    | '/_authenticated/modules'
    | '/_authenticated/onboarding'
    | '/_authenticated/overview'
    | '/_authenticated/posttest'
    | '/_authenticated/survey'
    | '/_authenticated/vr-simulation'
    | '/admin/$userId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SwissRoute: typeof SwissRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swiss': {
      id: '/swiss'
      path: '/swiss'
      fullPath: '/swiss'
      preLoaderRoute: typeof SwissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic': {
      id: '/_authenticated/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof AuthenticatedDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posttest': {
      id: '/_authenticated/posttest'
      path: '/posttest'
      fullPath: '/posttest'
      preLoaderRoute: typeof AuthenticatedPosttestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/survey': {
      id: '/_authenticated/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof AuthenticatedSurveyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vr-simulation': {
      id: '/_authenticated/vr-simulation'
      path: '/vr-simulation'
      fullPath: '/vr-simulation'
      preLoaderRoute: typeof AuthenticatedVrSimulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$userId': {
      id: '/admin/$userId'
      path: '/$userId'
      fullPath: '/admin/$userId'
      preLoaderRoute: typeof AdminUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticRoute: typeof AuthenticatedDiagnosticRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPosttestRoute: typeof AuthenticatedPosttestRoute
  AuthenticatedSurveyRoute: typeof AuthenticatedSurveyRoute
  AuthenticatedVrSimulationRoute: typeof AuthenticatedVrSimulationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticRoute: AuthenticatedDiagnosticRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPosttestRoute: AuthenticatedPosttestRoute,
  AuthenticatedSurveyRoute: AuthenticatedSurveyRoute,
  AuthenticatedVrSimulationRoute: AuthenticatedVrSimulationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminUserIdRoute: typeof AdminUserIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUserIdRoute: AdminUserIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SwissRoute: SwissRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
